export const strings = {
    REEF_DOCTOR_BRAND: 'Reef Doctor',
    HOMEPAGE_TITLE: 'ReefDoctor | UVC Training - Main Menu',
    HOMEPAGE_DESCRIPTION:
        "The main menu for ReefDoctor's UVC training. Browse information and images in the marine species catalog, or start an identification training workshop for each of the species categories.",
    HOMEPAGE_LINK: 'Reef Doctor - Back to main menu',
    HOMEPAGE_LOGO: 'Reef Doctor Logo',
    SPECIES_CATALOG_TITLE: 'ReefDoctor | UVC Training - Species Catalog',
    SPECIES_CATALOG_DESCRIPTION:
        'Select a category and UVC level to browse available species. Select a species to view identification details and sample images.',
    SPECIES_CATALOG: 'Species Catalog',
    CATEGORY_FISH: 'Fish',
    CATEGORY_INVERTEBRATE: 'Invertebrate',
    CATEGORY_BENTHIC: 'Benthic',
    CATEGORY_CORAL: 'Coral',
    CATEGORY_FISH_FAMILIES: 'Fish Families',
    CATEGORY_SEAGRASS: 'Seagrass',
    UVC_LEVEL_INDICATOR: 'Indicator',
    UVC_LEVEL_EXPERT: 'Expert',
    BUTTON_BROWSE_CATALOG: 'Browse Catalog',
    BUTTON_WORKSHOP: 'Workshop',
    BUTTON_QUIZ: 'Quiz',
    TUTORIAL_LEVEL_DIALOG_TITLE: 'UVC Level',
    TUTORIAL_LEVEL_DIALOG_BODY: 'Please select a UVC level for the {0}.',
    TUTORIAL_QUESTION_NUMBER: 'Question {0} of {1}',
    TUTORIAL_QUESTION_IMAGE: 'Question {0} Image',
    TUTORIAL_LOAD_ERROR: 'There was an error loading this tutorial session.',
    COMMAND_SHOW_ANSWER: 'Show answer',
    COMMAND_SPECIES_INFO: 'Species info',
    COMMAND_GO_TO_ANSWERS: 'Go to answers',
    COMMAND_BACK_TO_QUESTIONS: 'Back to questions',
    COMMAND_FINISH: 'Finish {0}',
}
