name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      - name: Code format check
        run: npm run format:check

      - name: Lint
        run: npm run lint:check

      - name: TS compile check
        run: npm run types:check

      - name: Run unit tests
        run: npm run test

      - name: Next build
        run: npm run next:build
