name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Code format check
        run: npm run format:check

      - name: Lint
        run: npm run lint:check

      - name: TS compile check
        run: npm run types:check

      - name: Run unit tests
        run: npm run test

      - name: Next build
        run: npm run next:build